### ISSUE TITLE
Clarity on audio options

### ISSUE THREAD

**Issue by dalanmiller** [LoneWanderer-GH/RaspiVWS#3]
Your solution is so great for introducing vlc via the source code that you have, I've been using it as my reference for the last couple of years. Thank you for putting this on the internet! 

I was curious if you also stream audio at all using this? I'm not having much success in getting audio off of the c920. I put all of my issues into this question on the [raspberry pi stack exchange](https://raspberrypi.stackexchange.com/questions/109417/unable-to-configure-pulseaudio-alsa-to-work-with-cvlc ). 

Do you have any guides/notes that aren't maybe public for getting the audio to work out?

**Comment by LoneWanderer-GH** [comment]
Thanks :)

I do not have anything more than what is in the repo. But I feel like streaming audio should be pretty much based on the same principles. VLC website and forums could be of help, that is where I got most of the information, with some other blogs links (that I never took care to save, but some googling should do the trick)

It seems you got quite much what you wanted on the raspi stack exchange.
As the answer says, the main problem is to give the correct audio source to VLC.

Do you need more here ? Otherwise, i'll close the ticket

**Comment by LoneWanderer-GH** [comment]
_I'm closing the issue since it is rather a question, and not directly related to code within the repo. (My original Stackoverflow post and the repo contain some insight in regards of audio device managers (alsa), if anything is worth being added, let me know; or even better, consider contributing)_
